//
// Autogenerated by Thrift Compiler (0.9.3)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;

var domain_ttypes = require('./domain_types')


var ttypes = require('./virtual-machine-service_types');
//HELPER FUNCTIONS AND STRUCTURES

com.onplan.client.VirtualMachineServiceRemote_getVirtualMachineInfo_args = function(args) {
};
com.onplan.client.VirtualMachineServiceRemote_getVirtualMachineInfo_args.prototype = {};
com.onplan.client.VirtualMachineServiceRemote_getVirtualMachineInfo_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

com.onplan.client.VirtualMachineServiceRemote_getVirtualMachineInfo_args.prototype.write = function(output) {
  output.writeStructBegin('VirtualMachineServiceRemote_getVirtualMachineInfo_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

com.onplan.client.VirtualMachineServiceRemote_getVirtualMachineInfo_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = new domain_ttypes.VirtualMachineInfo(args.success);
    }
  }
};
com.onplan.client.VirtualMachineServiceRemote_getVirtualMachineInfo_result.prototype = {};
com.onplan.client.VirtualMachineServiceRemote_getVirtualMachineInfo_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new domain_ttypes.VirtualMachineInfo();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

com.onplan.client.VirtualMachineServiceRemote_getVirtualMachineInfo_result.prototype.write = function(output) {
  output.writeStructBegin('VirtualMachineServiceRemote_getVirtualMachineInfo_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

com.onplan.client.VirtualMachineServiceRemoteClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
com.onplan.client.VirtualMachineServiceRemoteClient.prototype = {};
com.onplan.client.VirtualMachineServiceRemoteClient.prototype.seqid = function() { return this._seqid; }
com.onplan.client.VirtualMachineServiceRemoteClient.prototype.new_seqid = function() { return this._seqid += 1; }
com.onplan.client.VirtualMachineServiceRemoteClient.prototype.getVirtualMachineInfo = function(callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_getVirtualMachineInfo();
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_getVirtualMachineInfo();
  }
};

com.onplan.client.VirtualMachineServiceRemoteClient.prototype.send_getVirtualMachineInfo = function() {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('getVirtualMachineInfo', Thrift.MessageType.CALL, this.seqid());
  var args = new com.onplan.client.VirtualMachineServiceRemote_getVirtualMachineInfo_args();
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

com.onplan.client.VirtualMachineServiceRemoteClient.prototype.recv_getVirtualMachineInfo = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new com.onplan.client.VirtualMachineServiceRemote_getVirtualMachineInfo_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('getVirtualMachineInfo failed: unknown result');
};
com.onplan.client.VirtualMachineServiceRemoteProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
com.onplan.client.VirtualMachineServiceRemoteProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

com.onplan.client.VirtualMachineServiceRemoteProcessor.prototype.process_getVirtualMachineInfo = function(seqid, input, output) {
  var args = new com.onplan.client.VirtualMachineServiceRemote_getVirtualMachineInfo_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.getVirtualMachineInfo.length === 0) {
    Q.fcall(this._handler.getVirtualMachineInfo)
      .then(function(result) {
        var result = new com.onplan.client.VirtualMachineServiceRemote_getVirtualMachineInfo_result({success: result});
        output.writeMessageBegin("getVirtualMachineInfo", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("getVirtualMachineInfo", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.getVirtualMachineInfo(function (err, result) {
      if (err == null) {
        var result = new com.onplan.client.VirtualMachineServiceRemote_getVirtualMachineInfo_result((err != null ? err : {success: result}));
        output.writeMessageBegin("getVirtualMachineInfo", Thrift.MessageType.REPLY, seqid);
      } else {
        var result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("getVirtualMachineInfo", Thrift.MessageType.EXCEPTION, seqid);
      }
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

